analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#101010'
    - '#98979f'
    - '#294918'
    - '#afc149'
  brandStrength: 0.8125
  lightness: 0.0625
  rhythmicContrast: 0.4276623334735632
  saturation: 0.125
cta: {}
layout_spectrum: 0.028153
name: amspezzano
opengraph: {}
purpose: []
typography_spectrum: 0.884009
