analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#101010'
    - '#98979f'
    - '#294918'
    - '#afc149'
  brandStrength: 0.458333
  lightness: 0.75
  rhythmicContrast: 0.238738
  saturation: 0.759009
cta: {}
layout_spectrum: 1
name: amspezzano
opengraph: {}
purpose: []
typography_spectrum: 0.100225
