name: amspezzano
favicon: null
layout_spectrum: 0.13062
typography_spectrum: 0.884009
title: Intellectual Asthmatic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#101010'
    - '#98979f'
    - '#294918'
    - '#afc149'
  brandStrength: 0.8125
  lightness: 0.0625
  saturation: 0.125
  rhythmicContrast: 0.4276623334735632
purpose: []
